// ── printUtils.ts — Impresión de documentos via backend preview ──

function normalizeTipo(tipo: string): string {
  const t = tipo.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  if (t.includes('factura')) return 'factura';
  if (t.includes('albaran')) return 'albaran';
  if (t.includes('pedido')) return 'pedido';
  if (t.includes('presupuesto')) return 'presupuesto';
  return 'factura';
}

// ── MAIN PRINT FUNCTION ──
// Abre una URL real del backend que genera el HTML con el logo desde el servidor.
// Al ser una página real (no about:blank), las imágenes base64 funcionan sin restricciones.
// El HTML incluye <script>window.print()</script> para auto-imprimir.

export async function printDoc(tipo: string, datos: any): Promise<void> {
  const tipoNorm = normalizeTipo(tipo);
  const id = datos.id;
  if (!id) {
    console.error('[printUtils] No se encontró id en el documento');
    return;
  }

  const token = localStorage.getItem('accessToken') || '';
  const url = `/api/config/documentos/preview/${tipoNorm}/${id}?token=${encodeURIComponent(token)}`;

  const ventana = window.open(url, '_blank', 'width=900,height=700');
  if (!ventana) {
    alert('Permite las ventanas emergentes para este sitio para poder imprimir.');
  }
}

// Backward compatibility alias — old API was (doc, tipo), new is (tipo, doc)
export const imprimirDocumento = (doc: any, tipo: string) => printDoc(tipo, doc);

// Generate HTML via backend (for email sending)
export const generarHtmlDocumento = async (tipo: string, doc: any): Promise<string> => {
  const token = localStorage.getItem('accessToken') || '';
  const tipoNorm = normalizeTipo(tipo);
  const r = await fetch(`/api/config/documentos/preview/${tipoNorm}/${doc.id}?token=${encodeURIComponent(token)}`);
  return await r.text();
};

// Keep generateDocumentHTML export for any code that may reference it
export function generateDocumentHTML(_config: any, _tipo: string, _doc: any): string {
  return ''; // No longer used client-side — HTML is generated by backend
}

// ── Helper to generate default email subject/body for a document ──

export function getEmailDefaults(tipo: string, doc: any, empresaNombre?: string): { subject: string; body: string } {
  const t = normalizeTipo(tipo);
  const labels: Record<string, string> = { factura: 'Factura', presupuesto: 'Presupuesto', pedido: 'Pedido', albaran: 'Albarán' };
  const label = labels[t] || tipo;
  const num = doc.numeroCompleto || doc.numero || '';
  const emp = empresaNombre || '';

  const subject = `${label} ${num}${emp ? ' - ' + emp : ''}`;
  const body = `Estimado/a cliente,\n\nLe adjuntamos ${label.toLowerCase()} ${num}.\n\nQuedamos a su disposición para cualquier consulta.\n\nAtentamente,\n${emp}`;

  return { subject, body };
}
